### ISSUE TITLE
Clicking a drawer sometimes breaks the documentation

### ISSUE THREAD

**Issue by KonradLinkowski** [measuredco/puck#464]
Sometimes clicking on the drawer handle causes the documentation to fail

Handle:
https://puckeditor.com/docs/api-reference/components/drawer
![image](https://github.com/measuredco/puck/assets/26126510/250c73de-ec6d-4ee4-886a-258f2afdea78)

Error:
![image](https://github.com/measuredco/puck/assets/26126510/81d42d3c-1931-45a9-8fab-8ab07ed4146b)
```
framework-12a146e94cfcf7c4.js:9 TypeError: Cannot read properties of undefined (reading 'Orange')
    at reduceData (2246-61c58fe94e99ca2c.js:1:42800)
    at 2246-61c58fe94e99ca2c.js:1:62414
    at 2246-61c58fe94e99ca2c.js:1:45064
    at Object.fi [as useReducer] (framework-12a146e94cfcf7c4.js:9:62266)
    at t.useReducer (framework-12a146e94cfcf7c4.js:25:6061)
    at Puck (2246-61c58fe94e99ca2c.js:1:63453)
    at Xh (framework-12a146e94cfcf7c4.js:9:60990)
    at dj (framework-12a146e94cfcf7c4.js:9:72857)
    at x (framework-12a146e94cfcf7c4.js:9:120344)
    at Vk (framework-12a146e94cfcf7c4.js:9:99130)
 ```

**Comment by chrisvxd** [comment]
Looks like an issue with the insert component action in the reducer

<img width="1003" alt="image" src="https://github.com/measuredco/puck/assets/985961/bde24202-3549-45a0-978d-69290b491260">
